#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JellyBeanTracker.Mobile
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class JellyBeanGraph : System.Web.Mvc.WebViewPage<JellyBeanTracker.Shared.DisplayModels.ProfitReportModel>
{

#line hidden

public override void Execute()
{

#line 3 "JellyBeanGraph.cshtml"
  
    ViewBag.Title = "Jelly Bean Graph";


#line default
#line hidden
WriteLiteral("\r\n\r\n");


#line 7 "JellyBeanGraph.cshtml"
 if (JellyBeanTracker.Web.Globals.Native) {
    

#line default
#line hidden

#line 8 "JellyBeanGraph.cshtml"
Write(Html.Partial("JellyBeanTracker.Mobile.External.Web.Views.Shared.Header, JellyBeanTracker.Mobile", null));


#line default
#line hidden

#line 8 "JellyBeanGraph.cshtml"
                                                                                                            ;
}


#line default
#line hidden
WriteLiteral("\r\n\r\n\r\n<h2>Jelly Bean Price Graph</h2>\r\n\r\n<div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" style=\"min-width: 310px; height: 400px; margin: 0 auto\"");

WriteLiteral("></div>\r\n\r\n");


#line 17 "JellyBeanGraph.cshtml"
 if(JellyBeanTracker.Web.Globals.Native) {


#line default
#line hidden
WriteLiteral("\t<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"editVisible\"");

WriteLiteral(" title=\"Edit Visible\"");

WriteLiteral(" value=\"Edit Visible\"");

WriteLiteral(" />\r\n");

WriteLiteral("\t<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"getGraphData\"");

WriteLiteral(" title=\"Native Func\"");

WriteLiteral(" value=\"Native Func\"");

WriteLiteral(" />\r\n");


#line 20 "JellyBeanGraph.cshtml"
}


	

#line default
#line hidden

#line 29 "JellyBeanGraph.cshtml"
   


#line default
#line hidden
WriteLiteral("\r\n");


#line 31 "JellyBeanGraph.cshtml"
 if (JellyBeanTracker.Web.Globals.Native) {
    

#line default
#line hidden

#line 32 "JellyBeanGraph.cshtml"
Write(Html.Partial("JellyBeanTracker.Mobile.External.Web.Views.Shared.Footer, JellyBeanTracker.Mobile", null));


#line default
#line hidden

#line 32 "JellyBeanGraph.cshtml"
                                                                                                            ;
}


#line default
#line hidden
}
}
}
#pragma warning restore 1591
